### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by thinkholic** [fontlet/fontlet-explorer#6]

**Comment by thinkholic** [comment]
@pathumego ^

**Comment by thinkholic** [comment]
I'm proposing we go with MIT or BSD license, any other suggestions? @pathumego @THPubs

**Comment by pathumego** [comment]
I am suggesting go GPL V3 of later for the core stack.

**Comment by pathumego** [comment]
@thinkholic @THPubs thoughts?

**Comment by thinkholic** [comment]
@pathumego no probl. Let's go with [GPLV3](https://gist.github.com/kn9ts/cbe95340d29fc1aaeaa5dd5c059d2e60)

**Comment by pathumego** [comment]
@thinkholic Thanks! Sorry ive been busy! I have a local branch with all documentation files. Will push today
