### ISSUE TITLE
Font preview is set to the default thumbnails on Ubuntu

### ISSUE THREAD

**Issue by Malintha** [fontlet/fontlet-explorer#78]
STR:
Download and install a font.
Go to font explorer and view the font.
Thumbnails for the faces and letters are set to the default (I assume) on Ubuntu.
![selection_095](https://user-images.githubusercontent.com/3253761/48310112-1c53c400-e556-11e8-8d2d-477823fc4505.png)
![selection_094](https://user-images.githubusercontent.com/3253761/48310113-1c53c400-e556-11e8-8133-5618037babc1.png)

**Comment by pathumego** [comment]
@Malintha This is the Correct display of Abhaya Libre. Not the default :)
